[WIP] feat: Scan-Add a book
CMPUT301F20T05/CriEngine pull request #106
Opened 2020-11-05 23:57 UTC by shadowciaw

## Pull Request Description
#### Summary of changes/features added:
- added scanning book feature to add a book

#### Screenshots of UI changes (update with each new commit): 
![image](https://user-images.githubusercontent.com/43241070/98309511-e3edf180-1f87-11eb-9305-7554691f4f01.png)

#### Link to referenced github issue: 

## Pull Request Checklist
- [ ] Unit test written?
- [ ] (**For later in project**) Integration tests written?
- [ ] Java docs written?

## BLOCKED BY ERROR UPON CLICKING CONFIRM:
![image](https://user-images.githubusercontent.com/43241070/98309564-054edd80-1f88-11eb-8d8b-535142d63e6d.png)

2020-11-05 23:58 UTC, shadowciaw commented
will need to convert button to app's button later

2020-11-06 02:48 UTC, rwmilford reviewed
Looks good, but to be fair this isn't something I know a great deal about.  From what I do understand of it, it makes sense.

2020-11-08 23:22 UTC, AdityaHarvi requested changes

2020-11-08 23:22 UTC, AdityaHarvi commented on client/app/src/main/res/layout/activity_scan.xml
> +        android:text="@string/scan_confirm"
Buttons aren't formatted properly 😛 
Should be using the background and non-cap text

2020-11-21 20:37 UTC, AdityaHarvi commented on client/app/src/main/java/com/example/criengine/Activities/AddBookActivity.java
> +    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
java docs

2020-11-22 23:21 UTC, rjmah1 commented on client/app/src/main/java/com/example/criengine/Activities/AddBookActivity.java
> +
what's with these double spaces?

2020-11-22 23:23 UTC, rjmah1 commented on client/app/src/main/java/com/example/criengine/Activities/AddBookActivity.java
> +                } catch (IOException e) {
```suggestion
                } catch (Exception e) {
```

2020-11-22 23:27 UTC, shadowciaw commented on client/app/src/main/java/com/example/criengine/Activities/AddBookActivity.java
> +
idk im just crazy like that (fixed)

2020-11-22 23:28 UTC, rjmah1 commented on client/app/src/main/java/com/example/criengine/Activities/ScanActivity.java
> +     *  Once the user clicks yes or no on granting the app camera access, process the result here.
what's that extra space doin in the javadoc?

2020-11-22 23:28 UTC, AdityaHarvi approved these changes

2020-11-22 23:36 UTC, rjmah1 requested changes
code quality matters

2020-11-22 23:36 UTC, rjmah1 commented on client/app/src/main/java/com/example/criengine/Activities/ScanActivity.java
> +
this empty space

2020-11-22 23:38 UTC, rjmah1 approved these changes
lgtm

2020-11-22 23:38 UTC, merged