Feature/user profile fragment
CMPUT301F20T05/CriEngine pull request #154
Opened 2020-11-19 07:13 UTC by rjmah1

## Pull Request Description
#### Summary of changes/features added:
- placeholder search to access users
- user profiles but waiting for search to incorporate the listview of books

#### Screenshots of UI changes (update with each new commit): 
- 
![image](https://user-images.githubusercontent.com/43456924/99633223-c98e2c00-29fb-11eb-9290-ad103988ecd0.png)
![image](https://user-images.githubusercontent.com/43456924/99633252-d3179400-29fb-11eb-9409-d0627ba5c815.png)

#### Link to referenced github issue: 

## Pull Request Checklist
- [ ] Unit test written?
- [ ] (**For later in project**) Integration tests written?
- [ X ] Java docs written?

2020-11-19 18:12 UTC, AdityaHarvi commented
The first picture you posted isn't actually needed in the app. If the main purpose of it is to just navigate to the non-owner profile view, then it should not be added.
It will just end up causing merge conflicts for ralph since hes working on search rn

2020-11-19 18:14 UTC, rjmah1 commented
> The first picture you posted isn't actually needed in the app. If the main purpose of it is to just navigate to the non-owner profile view, then it should not be added.
> It will just end up causing merge conflicts for ralph since hes working on search rn

it's somewhat needed because it shows the contract that allows you to use the user profile activity

2020-11-19 23:42 UTC, ducklin5 requested changes

2020-11-19 23:42 UTC, ducklin5 commented on client/app/src/main/res/layout/activity_user_profile.xml
> +        <include
We need to make other user's profile activity not editable. I see we are sharing this part. This is good.

2020-11-19 23:42 UTC, ducklin5 commented on client/app/src/main/java/com/example/criengine/Activities/UserProfileActivity.java
> +        userBooksListView = findViewById(R.id.user_books_listview);
can we also get the EditTextViews of: "user_profile_text", "bio_text", "phone_text", "addr_text"
and make it so they are not editable... ie https://github.com/CMPUT301F20T05/CriEngine/blob/07153950cd56a1b526ad05d34209142deb45fada/client/app/src/main/java/com/example/criengine/Fragments/MyProfileFragment.java#L35-L46

2020-11-19 23:42 UTC, ducklin5 commented on client/app/src/main/res/layout/activity_user_profile.xml
> +    <fragment
Also can we prevent the bottom nav fragment from reacting to the keyboard? @AdityaHarvi  had this issue as well

2020-11-19 23:44 UTC, ducklin5 commented on client/app/src/main/res/layout/activity_user_profile.xml
> +    <fragment
I think you can fix this by putting the fragment inside the linear layout and having the ListView fill up the remaining space

2020-11-20 02:42 UTC, ducklin5 approved these changes
LGTM! 🚀

2020-11-23 01:00 UTC, rwmilford reviewed
Besides my own comment and Azeez's it looks good.

2020-11-23 01:02 UTC, AdityaHarvi commented on client/app/src/main/java/com/example/criengine/Activities/ProfileActivity.java
>      protected void onCreate(Bundle savedInstanceState) {
Optional but you can copy/paste javadocs for this part from other fragments

2020-11-23 01:07 UTC, rjmah1 commented on client/app/src/main/java/com/example/criengine/Activities/RootActivity.java
> +                    return new PlaceholderSearchFragment();
yes, it's just so that you get the hint on how you need to call userProfiles

2020-11-23 01:15 UTC, AdityaHarvi approved these changes

2020-11-23 01:20 UTC, merged